version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && cat ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  build-and-test:
    jobs:
      - build-and-test
  publish:
    jobs:
      - publish:
          context: personal
      - build-and-test
