
# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm test
          - run: npm run build

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo _auth=$NPM_TOKEN >> .npmrc && echo email=$NPM_EMAIL >> .npmrc && always-auth=true >> .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - publish:
          requires:
            - test
#           filters:
#             tags:
#               only: /^v.*/
#             branches:
#               ignore: /.*/
