version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo _auth=$NPM_TOKEN >> .npmrc && echo email=$NPM_EMAIL >> .npmrc && always-auth=true >> .npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  build-and-test:
    jobs:
      - build-and-test
  publish:
    jobs:
      - build-and-test
      - publish
